### ISSUE TITLE
Emacs Crashes with "Memory Exhausted" Under ld-linux.so On Some Systems

### ISSUE THREAD

**Issue by Shinmera** [portacle/portacle#18]
This now happens on my Arch system (I know it worked some months ago!) but still doesn't happen on my Mint test system. Very strange.

**Comment by Shinmera** [comment]
What I've found so far is this: on some systems emacs simply crashes when launched under ld-linux.so, regardless of Portacle entirely. On my Arch systems I can reproduce this. On the Mint system I cannot.

The following mailing list thread hints that it might be a kernel related / deep emacs problem:
http://gnu.emacs.bug.narkive.com/6nDY0MRn/lib-ld-linux-so-2-usr-bin-emacs-fails-memory-exhausted

**Comment by Shinmera** [comment]
Thinking things through this seems even more suspect. Given that the whole thing works if ported from the Mint system to the Arch system I'm not sure if the above discussion applies to this, especially considering its age.

I suppose one thing that might be worth looking into is checking the values of `ELF_ET_DYN_BASE` on the respective systems, but I don't know how to go about that.

**Comment by Shinmera** [comment]
Here's the filed bug ticket on emacs: https://debbugs.gnu.org/cgi/bugreport.cgi?bug=24708

**Comment by Shinmera** [comment]
It seems that on more recent Emacs versions (master, not yet 26.0) this problem has vanished. Since 26 doesn't have an rc yet and isn't fully released, I'll hold off. If this should be fixed entirely though, that would be very great news indeed.

**Comment by Wilfred** [comment]
FWIW I patched emacs.sh to:

```bash
readonly TAG=emacs-26.0.91
```

but even after re-running emacs.sh, I still get 'memory exhausted' when starting portacle.

**Comment by Shinmera** [comment]
Interesting. I still wish I had any conclusive idea on why this happens, and especially why it only sometimes happens.

**Comment by Shinmera** [comment]
In all my tests 26.1 fixes this issue.
